// src/routes/admin/+page.svelte
<script lang="ts">
	import '$lib/styles/app.css';
	import { enhance } from '$app/forms';
	import type { PageData } from './$types';

	let { data, form }: { data: PageData; form: Record<string, any> | null } = $props();
	const rows = $derived((data.projects ?? []) as Record<string, any>[]);

	const CLUSTERS = ['ai', 'fullstack', 'automation', 'embedded'];
	const GROUPS = [
		{ key: 'featured', label: 'featured', hint: 'split card in selected work + full node on the map' },
		{ key: 'archive', label: 'archive', hint: 'one row in the archive + a pill on the map' },
		{ key: 'hidden', label: 'hidden', hint: 'draft, hidden from the public site' }
	];
	const byStatus = (s: string) => rows.filter((p) => p.status === s);
	const quickSubmit = (e: Event) => (e.currentTarget as HTMLSelectElement).form?.requestSubmit();

	// Single-project editor. Values are copied into local $state on open and
	// two-way bound, so the fields always hold the real row values. (The old
	// admin rendered every project's form at once with unbound inputs, which
	// could submit blank and wipe a row.) Array/jsonb columns edit as text.
	let editing = $state<Record<string, any> | null>(null);

	function openEdit(p: Record<string, any>) {
		editing = {
			id: p.id,
			title: p.title ?? '',
			summary: p.summary ?? '',
			why: p.why ?? '',
			cluster: p.cluster ?? 'fullstack',
			status: p.status ?? 'hidden',
			year: p.year ?? '',
			sort_order: p.sort_order ?? 100,
			map_x: p.map_x ?? 50,
			map_y: p.map_y ?? 50,
			github_url: p.github_url ?? '',
			live_url: p.live_url ?? '',
			loom_id: p.loom_id ?? '',
			cover_image: p.cover_image ?? '',
			outcome: Array.isArray(p.outcome) ? p.outcome.join('\n') : '',
			schematic: Array.isArray(p.schematic) ? p.schematic.join(', ') : '',
			stack: Array.isArray(p.stack) ? p.stack.join(', ') : '',
			features: Array.isArray(p.features)
				? p.features.map((f: any) => `${f.label ?? ''} :: ${f.detail ?? ''}`).join('\n')
				: ''
		};
	}
	const closeEdit = () => (editing = null);

	// close the editor once a save round-trips successfully
	function saveSubmit() {
		return async ({ result, update }: { result: { type: string }; update: () => Promise<void> }) => {
			await update();
			if (result.type === 'success') editing = null;
		};
	}
</script>

<svelte:head><title>admin, adyu portfolio</title></svelte:head>

<div class="app">
	<main class="wrap admin">
		<div class="head">
			<h1>admin</h1>
			{#if data.configured && data.user}
				<span class="whoami mono">signed in as {data.user.email}</span>
			{/if}
		</div>

		{#if data.loginError}<p class="msg err">login failed: {data.loginError}</p>{/if}

		{#if !data.configured}
			<p class="note">
				supabase is not configured, so this is running on seed data. locally: set
				PUBLIC_SUPABASE_URL and PUBLIC_SUPABASE_ANON_KEY in .env. on cloudflare (workers): they
				ship committed in wrangler.jsonc, so just redeploy. run supabase-schema.sql once either
				way.
			</p>
		{:else if !data.user}
			<form method="POST" action="?/login" use:enhance class="login">
				<p class="note">sign in with a magic link. only the invited owner email works.</p>
				<label>email <input name="email" type="email" placeholder="you@example.com" required /></label>
				<button class="btn" type="submit">send magic link</button>
				{#if form?.sent}<p class="msg ok">check your inbox for the link.</p>{/if}
				{#if form?.message}<p class="msg err">{form.message}</p>{/if}
			</form>
		{:else if editing}
			<form method="POST" action="?/save" use:enhance={saveSubmit} class="editor">
				<div class="editor-bar">
					<div class="editor-title">
						<span class="mono eyebrow">editing project</span>
						<h2>{editing.title || editing.id}</h2>
					</div>
					<div class="bar-actions">
						<button type="button" class="btn btn--ghost sm" onclick={closeEdit}>cancel</button>
						<button type="submit" class="btn sm">save changes</button>
					</div>
				</div>

				{#if form?.message}<p class="msg err">{form.message}</p>{/if}
				<input type="hidden" name="id" value={editing.id} />

				<fieldset>
					<legend>basics</legend>
					<label class="wide">title <input name="title" bind:value={editing.title} /></label>
					<div class="grid3">
						<label>status
							<select name="status" bind:value={editing.status}>
								{#each GROUPS as g (g.key)}<option value={g.key}>{g.label}</option>{/each}
							</select>
						</label>
						<label>cluster
							<select name="cluster" bind:value={editing.cluster}>
								{#each CLUSTERS as c (c)}<option value={c}>{c}</option>{/each}
							</select>
						</label>
						<label>year <input name="year" bind:value={editing.year} /></label>
					</div>
				</fieldset>

				<fieldset>
					<legend>content</legend>
					<label class="wide">summary <textarea name="summary" rows="3" bind:value={editing.summary}></textarea></label>
					<label class="wide">why i built it <textarea name="why" rows="3" bind:value={editing.why}></textarea></label>
					<label class="wide">how it works <span class="hint">one per line, as "label :: detail"</span>
						<textarea name="features" rows="6" bind:value={editing.features}></textarea></label>
					<label class="wide">outcomes <span class="hint">one per line</span>
						<textarea name="outcome" rows="2" bind:value={editing.outcome}></textarea></label>
				</fieldset>

				<fieldset>
					<legend>links</legend>
					<label class="wide">github url <input name="github_url" bind:value={editing.github_url} placeholder="https://github.com/..." /></label>
					<label class="wide">live site url <input name="live_url" bind:value={editing.live_url} placeholder="https://..." /></label>
					<label class="wide">loom walkthrough id <input name="loom_id" bind:value={editing.loom_id} placeholder="the part after loom.com/share/" /></label>
					<label class="wide">cover image url <span class="hint">card poster when there is no loom</span>
						<input name="cover_image" bind:value={editing.cover_image} placeholder="https://..." /></label>
				</fieldset>

				<fieldset>
					<legend>map + tech</legend>
					<div class="grid3">
						<label>sort order <input name="sort_order" type="number" bind:value={editing.sort_order} /></label>
						<label>map x <input name="map_x" type="number" bind:value={editing.map_x} /></label>
						<label>map y <input name="map_y" type="number" bind:value={editing.map_y} /></label>
					</div>
					<label class="wide">schematic steps <span class="hint">comma separated</span>
						<input name="schematic" bind:value={editing.schematic} /></label>
					<label class="wide">stack <span class="hint">comma separated</span>
						<input name="stack" bind:value={editing.stack} /></label>
				</fieldset>

				<div class="editor-foot">
					<button type="button" class="btn btn--ghost sm" onclick={closeEdit}>cancel</button>
					<button type="submit" class="btn sm">save changes</button>
				</div>
			</form>
		{:else}
			<div class="toolbar">
				<div class="flash" aria-live="polite">
					{#if form?.synced != null}<span class="msg ok">synced {form.synced} of {form.total} from github</span>{/if}
					{#if form?.saved}<span class="msg ok">saved {form.saved}</span>{/if}
					{#if form?.created}<span class="msg ok">created {form.created}</span>{/if}
					{#if form?.message}<span class="msg err">{form.message}</span>{/if}
				</div>
				<div class="tools">
					<form method="POST" action="?/sync" use:enhance><button class="btn btn--ghost sm" type="submit">sync from github</button></form>
					<form method="POST" action="?/createDraft" use:enhance><button class="btn btn--ghost sm" type="submit">new draft</button></form>
					<form method="POST" action="?/logout" use:enhance><button class="btn btn--ghost sm" type="submit">log out</button></form>
				</div>
			</div>

			<p class="lead mono">status is the whole lever. move a project between groups with its dropdown, or open it to edit everything.</p>

			{#each GROUPS as g (g.key)}
				{@const items = byStatus(g.key)}
				<section class="group">
					<div class="group-head">
						<h2>{g.label} <span class="count mono">{items.length}</span></h2>
						<span class="group-hint mono">{g.hint}</span>
					</div>
					{#if items.length === 0}
						<p class="empty mono">nothing here yet.</p>
					{:else}
						<ul class="plist">
							{#each items as p (p.id)}
								<li class="prow">
									<div class="pmain">
										<span class="ptitle">{p.title || p.id}</span>
										<span class="pmeta mono">{p.cluster}{p.year ? ' · ' + p.year : ''}</span>
									</div>
									<div class="pactions">
										<form method="POST" action="?/setStatus" use:enhance class="statusform">
											<input type="hidden" name="id" value={p.id} />
											<label class="sr-only" for="s-{p.id}">status for {p.title || p.id}</label>
											<select id="s-{p.id}" name="status" value={p.status} onchange={quickSubmit}>
												{#each GROUPS as g2 (g2.key)}<option value={g2.key}>{g2.label}</option>{/each}
											</select>
										</form>
										<button type="button" class="btn btn--ghost sm" onclick={() => openEdit(p)}>edit</button>
									</div>
								</li>
							{/each}
						</ul>
					{/if}
				</section>
			{/each}
		{/if}
	</main>
</div>

<style>
	.admin {
		padding: 120px 0 96px;
		display: flex;
		flex-direction: column;
		gap: 28px;
	}
	.head {
		display: flex;
		align-items: baseline;
		justify-content: space-between;
		flex-wrap: wrap;
		gap: 12px;
		border-bottom: 1px solid var(--border);
		padding-bottom: 16px;
	}
	.admin h1 { font-size: 36px; }
	.whoami { color: var(--ink-soft); }
	.note, .lead { color: var(--ink-soft); max-width: 68ch; line-height: 1.6; }
	.hint { color: var(--ink-soft); font-size: 12px; font-weight: 400; text-transform: none; }

	/* messages */
	.msg { font-size: 13px; font-weight: 500; text-transform: lowercase; }
	.msg.ok { color: var(--accent); }
	.msg.err { color: #ba1a1a; }

	/* login */
	.login { max-width: 420px; display: flex; flex-direction: column; gap: 14px; }

	/* toolbar */
	.toolbar {
		display: flex;
		align-items: center;
		justify-content: space-between;
		flex-wrap: wrap;
		gap: 12px;
	}
	.tools { display: flex; gap: 8px; flex-wrap: wrap; }
	.flash { min-height: 18px; }

	/* status groups */
	.group { display: flex; flex-direction: column; gap: 10px; }
	.group-head { display: flex; align-items: baseline; gap: 14px; flex-wrap: wrap; }
	.group-head h2 { font-size: 20px; display: flex; align-items: baseline; gap: 8px; }
	.count {
		color: var(--ink-soft);
		border: 1px solid var(--border);
		padding: 1px 8px;
		font-size: 11px;
	}
	.group-hint { color: var(--ink-soft); }
	.empty { color: var(--ink-soft); padding: 8px 0; }

	.plist { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; }
	.prow {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 16px;
		padding: 14px 16px;
		border: 1px solid var(--border);
		border-top: 0;
		background: var(--panel);
	}
	.plist .prow:first-child { border-top: 1px solid var(--border); }
	.prow:hover { background: var(--panel-hover); }
	.pmain { display: flex; flex-direction: column; gap: 3px; min-width: 0; }
	.ptitle { font-size: 17px; text-transform: lowercase; }
	.pmeta { color: var(--ink-soft); }
	.pactions { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }
	.statusform { margin: 0; }

	/* editor */
	.editor { display: flex; flex-direction: column; gap: 22px; }
	.editor-bar, .editor-foot {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 12px;
		flex-wrap: wrap;
	}
	.editor-bar { border-bottom: 1px solid var(--border); padding-bottom: 16px; }
	.editor-foot { border-top: 1px solid var(--border); padding-top: 16px; }
	.editor-title { display: flex; flex-direction: column; gap: 4px; }
	.editor-title h2 { font-size: 24px; }
	.eyebrow { color: var(--ink-soft); }
	.bar-actions { display: flex; gap: 8px; }

	fieldset {
		border: 1px solid var(--border);
		padding: 20px;
		display: flex;
		flex-direction: column;
		gap: 16px;
	}
	legend {
		font-family: var(--font-body);
		font-size: 12px;
		font-weight: 600;
		letter-spacing: 0.08em;
		text-transform: uppercase;
		color: var(--ink-soft);
		padding: 0 8px;
	}
	.grid3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }

	label {
		display: flex;
		flex-direction: column;
		gap: 6px;
		font-size: 13px;
		color: var(--ink-soft);
		text-transform: lowercase;
	}

	/* controls */
	select, input, textarea {
		font-family: var(--font-body);
		font-size: 15px;
		color: var(--ink);
		background: var(--bg);
		border: 1px solid var(--border-strong);
		padding: 10px 12px;
	}
	textarea { resize: vertical; line-height: 1.5; }
	select:focus, input:focus, textarea:focus {
		outline: 2px solid var(--focus);
		outline-offset: 1px;
		border-color: var(--focus);
	}
	.prow select { padding: 8px 10px; font-size: 13px; }

	/* smaller buttons for dense admin rows (overrides the global .btn size) */
	.pactions .btn.sm, .tools .btn.sm, .bar-actions .btn.sm, .editor-foot .btn.sm {
		padding: 9px 16px;
		font-size: 13px;
		letter-spacing: 0.03em;
	}

	.sr-only {
		position: absolute;
		width: 1px; height: 1px;
		padding: 0; margin: -1px;
		overflow: hidden; clip: rect(0, 0, 0, 0);
		white-space: nowrap; border: 0;
	}

	@media (max-width: 640px) {
		.admin { padding: 96px 0 64px; }
		.grid3 { grid-template-columns: 1fr; }
		.prow { flex-direction: column; align-items: stretch; }
		.pactions { justify-content: space-between; }
	}
</style>

// src/routes/admin/index.tsx
import { component$, useSignal, useStyles$, useTask$ } from '@qwik.dev/core';
import { Form, routeAction$, routeLoader$, type DocumentHead } from '@qwik.dev/router';
import { buildProjectPatch, loomThumb, type AdminForm } from '~/lib/server/admin';
import { supabaseConfigured } from '~/lib/server/env';
import {
	createServerSupabase,
	forgetVerifiedUser,
	getVerifiedUser
} from '~/lib/server/supabase';
import { runRepoSync } from '~/lib/server/sync';
import styles from './admin.css?inline';

type Row = Record<string, any>;

const CLUSTERS = ['ai', 'fullstack', 'automation', 'embedded'];
const SOURCES = ['manual', 'github'];
const GROUPS = [
	{ key: 'featured', label: 'featured', hint: 'highlighted in selected work + on the map' },
	{ key: 'archive', label: 'archive', hint: 'in the full project collection + on the map' },
	{ key: 'hidden', label: 'hidden', hint: 'draft, hidden from the public site' }
];

// ---------------------------------------------------------------- server

export const useAdminData = routeLoader$(async (event) => {
	// Per-user page: never cached anywhere.
	event.headers.set('Cache-Control', 'private, no-store');
	// A failed magic-link exchange redirects here with ?error=; surface it.
	const loginError = event.url.searchParams.get('error');
	const supabase = createServerSupabase(event);
	if (!supabaseConfigured(event) || !supabase) {
		return { configured: false, user: null, projects: [] as Row[], loginError, loadError: null };
	}
	const user = await getVerifiedUser(event);
	if (!user) return { configured: true, user: null, projects: [] as Row[], loginError, loadError: null };

	const { data, error } = await supabase
		.from('projects')
		.select('*')
		.order('sort_order', { ascending: true });
	return {
		configured: true,
		user: { email: user.email ?? '' },
		projects: (data ?? []) as Row[],
		loginError,
		loadError: error ? error.message : null
	};
},
// The editor renders client-side from these rows, so ship them with the page
// (owner-only HTML) instead of lazily re-fetching the loader on first use.
{ serializationStrategy: 'always' });

/** Every project mutation re-validates the session with getUser(). RLS on the
 *  projects table stays the database-side guard. */
async function requireOwner(event: Parameters<typeof getVerifiedUser>[0]) {
	if (!createServerSupabase(event)) return null;
	return getVerifiedUser(event);
}

export const useLogin = routeAction$(async (data, event) => {
	const supabase = createServerSupabase(event);
	if (!supabase) return event.fail(400, { message: 'supabase not configured' });
	const email = String(data.email ?? '').trim();
	if (!email) return event.fail(400, { message: 'email required' });
	const { error } = await supabase.auth.signInWithOtp({
		email,
		options: { emailRedirectTo: `${event.url.origin}/auth/callback` }
	});
	if (error) return event.fail(400, { message: error.message });
	return { sent: true };
});

export const useLogout = routeAction$(
	async (_data, event) => {
		await createServerSupabase(event)?.auth.signOut();
		forgetVerifiedUser(event);
		return { ok: true };
	},
	{ invalidate: [useAdminData] }
);

export const useSave = routeAction$(
	async (data, event) => {
		const user = await requireOwner(event);
		if (!user) return event.fail(401, { message: 'unauthorized' });
		const supabase = createServerSupabase(event)!;
		const f = data as AdminForm;
		const id = String(f.id ?? '');
		if (!id) return event.fail(400, { message: 'missing id' });

		// Merge onto the existing row: only fields the form submitted are written.
		const { data: existing, error: readErr } = await supabase
			.from('projects')
			.select('*')
			.eq('id', id)
			.maybeSingle();
		if (readErr) return event.fail(400, { message: readErr.message });
		if (!existing) return event.fail(404, { message: 'project not found' });

		const patch = buildProjectPatch(f, existing as Row);
		if (Object.keys(patch).length === 0) return { saved: id };
		const { error } = await supabase.from('projects').update(patch).eq('id', id);
		if (error) return event.fail(400, { message: error.message });

		// best-effort: cache the loom oEmbed thumbnail in a second write, so a loom
		// hiccup or an un-migrated loom_thumb column can never break the save itself.
		if (Object.prototype.hasOwnProperty.call(f, 'loom_id')) {
			const lid = String(f.loom_id ?? '').trim();
			const thumb = lid ? await loomThumb(lid) : null;
			await supabase.from('projects').update({ loom_thumb: thumb }).eq('id', id);
		}
		return { saved: id };
	},
	{ invalidate: [useAdminData] }
);

export const useSetStatus = routeAction$(
	async (data, event) => {
		const user = await requireOwner(event);
		if (!user) return event.fail(401, { message: 'unauthorized' });
		const id = String(data.id ?? '');
		const status = String(data.status ?? 'hidden');
		const { error } = await createServerSupabase(event)!
			.from('projects')
			.update({ status })
			.eq('id', id);
		if (error) return event.fail(400, { message: error.message });
		return { statusSet: id };
	},
	{ invalidate: [useAdminData] }
);

export const useCreateDraft = routeAction$(
	async (_data, event) => {
		const user = await requireOwner(event);
		if (!user) return event.fail(401, { message: 'unauthorized' });
		const id = `draft_${Date.now()}`;
		const { error } = await createServerSupabase(event)!
			.from('projects')
			.insert({ id, title: 'new project', status: 'hidden', source: 'manual' });
		if (error) return event.fail(400, { message: error.message });
		return { created: id };
	},
	{ invalidate: [useAdminData] }
);

export const useSync = routeAction$(
	async (_data, event) => {
		const user = await requireOwner(event);
		if (!user) return event.fail(401, { message: 'unauthorized' });
		const result = await runRepoSync(event);
		if (!result.ok) return event.fail(result.status, { message: `sync failed: ${result.error}` });
		return result.mode === 'supabase'
			? { synced: result.added, total: result.total }
			: { dryRun: true, total: result.count };
	},
	{ invalidate: [useAdminData] }
);

// ---------------------------------------------------------------- client

const failMessage = (v: unknown): string | null =>
	v && typeof v === 'object' && 'failed' in v ? String((v as { message?: unknown }).message ?? 'failed') : null;

const lines = (v: unknown, sep: string) => (Array.isArray(v) ? v.join(sep) : '');
const featureLines = (v: unknown) =>
	Array.isArray(v) ? v.map((f: Row) => `${f?.label ?? ''} :: ${f?.detail ?? ''}`).join('\n') : '';

export default component$(() => {
	useStyles$(styles);
	const data = useAdminData();
	const login = useLogin();
	const logout = useLogout();
	const save = useSave();
	const setStatus = useSetStatus();
	const createDraft = useCreateDraft();
	const sync = useSync();

	// Single-project editor. Fields start from the real row values, so a save
	// only ever submits what the row already holds plus the owner's edits.
	const editingId = useSignal<string | null>(null);
	const flash = useSignal<{ ok: boolean; text: string } | null>(null);

	useTask$(({ track }) => {
		const v = track(() => save.value);
		if (!v) return;
		const err = failMessage(v);
		if (err) {
			flash.value = { ok: false, text: err };
		} else if ('saved' in v) {
			flash.value = { ok: true, text: `saved ${v.saved}` };
			editingId.value = null; // close the editor once a save round-trips
		}
	});
	useTask$(({ track }) => {
		const v = track(() => sync.value);
		if (!v) return;
		const err = failMessage(v);
		flash.value = err
			? { ok: false, text: err }
			: 'dryRun' in v
				? { ok: true, text: `dry run: ${v.total} repos found, nothing saved` }
				: 'synced' in v
					? { ok: true, text: `synced ${v.synced} of ${v.total} from github` }
					: null;
	});
	useTask$(({ track }) => {
		const v = track(() => createDraft.value);
		if (!v) return;
		const err = failMessage(v);
		flash.value = err ? { ok: false, text: err } : 'created' in v ? { ok: true, text: `created ${v.created}` } : null;
	});
	useTask$(({ track }) => {
		const v = track(() => setStatus.value);
		const err = failMessage(v);
		if (err) flash.value = { ok: false, text: err };
	});

	const d = data.value;
	const rows = d.projects;
	const editing = editingId.value ? rows.find((r) => r.id === editingId.value) ?? null : null;
	const loginErr = failMessage(login.value);
	const saveErr = failMessage(save.value);

	return (
		<div class="adm">
			<main class="adm-wrap">
				<div class="head">
					<h1>admin</h1>
					{d.configured && d.user && <span class="whoami mono">signed in as {d.user.email}</span>}
				</div>

				{d.loginError && <p class="msg err">login failed: {d.loginError}</p>}
				{d.loadError && <p class="msg err">could not load projects: {d.loadError}</p>}

				{!d.configured ? (
					<p class="note">
						supabase is not configured, so this is running on seed data. locally: run the built worker
						with wrangler (it reads PUBLIC_SUPABASE_URL and PUBLIC_SUPABASE_ANON_KEY from
						wrangler.jsonc). on cloudflare (workers): they ship committed in wrangler.jsonc, so just
						redeploy. run supabase-schema.sql once either way.
					</p>
				) : !d.user ? (
					<Form action={login} class="login">
						<p class="note">sign in with a magic link. only the invited owner email works.</p>
						<label>
							email <input name="email" type="email" placeholder="you@example.com" autocomplete="email" required />
						</label>
						<button class="btn" type="submit" disabled={login.isRunning}>
							send magic link
						</button>
						<div aria-live="polite">
							{login.value && 'sent' in login.value && <p class="msg ok">check your inbox for the link.</p>}
							{loginErr && <p class="msg err">{loginErr}</p>}
						</div>
					</Form>
				) : editing ? (
					<Form action={save} class="editor" key={editing.id}>
						<div class="editor-bar">
							<div class="editor-title">
								<span class="mono eyebrow">editing project</span>
								<h2>{editing.title || editing.id}</h2>
							</div>
							<div class="bar-actions">
								<button type="button" class="btn btn--ghost" onClick$={() => (editingId.value = null)}>
									cancel
								</button>
								<button type="submit" class="btn" disabled={save.isRunning}>
									save changes
								</button>
							</div>
						</div>

						{saveErr && <p class="msg err">{saveErr}</p>}
						<input type="hidden" name="id" value={editing.id} />

						<fieldset>
							<legend>basics</legend>
							<label>
								title <input name="title" value={editing.title ?? ''} />
							</label>
							<div class="grid4">
								<label>
									status
									<select name="status">
										{GROUPS.map((g) => (
											<option key={g.key} value={g.key} selected={(editing.status ?? 'hidden') === g.key}>
												{g.label}
											</option>
										))}
									</select>
								</label>
								<label>
									cluster
									<select name="cluster">
										{CLUSTERS.map((c) => (
											<option key={c} value={c} selected={(editing.cluster ?? 'fullstack') === c}>
												{c}
											</option>
										))}
									</select>
								</label>
								<label>
									year <input name="year" value={editing.year ?? ''} />
								</label>
								<label>
									source
									<select name="source">
										{SOURCES.map((s) => (
											<option key={s} value={s} selected={(editing.source ?? 'manual') === s}>
												{s}
											</option>
										))}
									</select>
								</label>
							</div>
						</fieldset>

						<fieldset>
							<legend>content</legend>
							<label>
								summary <textarea name="summary" rows={3} value={editing.summary ?? ''} />
							</label>
							<label>
								why i built it <textarea name="why" rows={3} value={editing.why ?? ''} />
							</label>
							<label>
								<span>
									how it works <span class="hint">one per line, as "label :: detail"</span>
								</span>
								<textarea name="features" rows={6} value={featureLines(editing.features)} />
							</label>
							<label>
								<span>
									outcomes <span class="hint">one per line</span>
								</span>
								<textarea name="outcome" rows={2} value={lines(editing.outcome, '\n')} />
							</label>
						</fieldset>

						{'system_detail' in editing && (
							<fieldset>
								<legend>system detail</legend>
								<p class="hint">
									shown as the system legend in the project detail. other stored keys (like the diagram
									metadata) are kept as they are.
								</p>
								<label>
									summary <textarea name="sd_summary" rows={2} value={editing.system_detail?.summary ?? ''} />
								</label>
								<label>
									delivery status{' '}
									<input name="sd_delivery_status" value={editing.system_detail?.deliveryStatus ?? ''} />
								</label>
								<label>
									<span>
										legend <span class="hint">one per line, as "label :: detail"</span>
									</span>
									<textarea name="sd_legend" rows={6} value={featureLines(editing.system_detail?.legend)} />
								</label>
							</fieldset>
						)}

						<fieldset>
							<legend>links + media</legend>
							<label>
								github url <input name="github_url" value={editing.github_url ?? ''} placeholder="https://github.com/..." />
							</label>
							<label>
								live site url <input name="live_url" value={editing.live_url ?? ''} placeholder="https://..." />
							</label>
							<label>
								<span>
									loom walkthrough id{' '}
									<span class="hint">fallback only: the site plays the local demo video when one exists</span>
								</span>
								<input name="loom_id" value={editing.loom_id ?? ''} placeholder="the part after loom.com/share/" />
							</label>
							{editing.loom_thumb && <p class="readonly">cached loom thumbnail: {editing.loom_thumb}</p>}
							<label>
								<span>
									cover image url <span class="hint">card poster when there is no video</span>
									{!('cover_image' in editing) && (
										<span class="hint"> (this database has no cover_image column yet; a value will fail to save)</span>
									)}
								</span>
								<input name="cover_image" value={editing.cover_image ?? ''} placeholder="https://..." />
							</label>
						</fieldset>

						<fieldset>
							<legend>map + tech</legend>
							<div class="grid3">
								<label>
									sort order <input name="sort_order" type="number" step="any" value={editing.sort_order ?? 100} />
								</label>
								<label>
									map x <input name="map_x" type="number" step="any" value={editing.map_x ?? 50} />
								</label>
								<label>
									map y <input name="map_y" type="number" step="any" value={editing.map_y ?? 50} />
								</label>
							</div>
							<label>
								<span>
									schematic steps <span class="hint">comma separated</span>
								</span>
								<input name="schematic" value={lines(editing.schematic, ', ')} />
							</label>
							<label>
								<span>
									stack <span class="hint">comma separated</span>
								</span>
								<input name="stack" value={lines(editing.stack, ', ')} />
							</label>
						</fieldset>

						<div class="editor-foot">
							<button type="button" class="btn btn--ghost" onClick$={() => (editingId.value = null)}>
								cancel
							</button>
							<button type="submit" class="btn" disabled={save.isRunning}>
								save changes
							</button>
						</div>
					</Form>
				) : (
					<>
						<div class="toolbar">
							<div class="flash" aria-live="polite">
								{flash.value && <span class={['msg', flash.value.ok ? 'ok' : 'err']}>{flash.value.text}</span>}
							</div>
							<div class="tools">
								<Form action={sync}>
									<button class="btn btn--ghost" type="submit" disabled={sync.isRunning}>
										sync from github
									</button>
								</Form>
								<Form action={createDraft}>
									<button class="btn btn--ghost" type="submit" disabled={createDraft.isRunning}>
										new draft
									</button>
								</Form>
								<Form action={logout}>
									<button class="btn btn--ghost" type="submit" disabled={logout.isRunning}>
										log out
									</button>
								</Form>
							</div>
						</div>

						<p class="lead mono">
							status is the whole lever. move a project between groups with its dropdown, or open it to edit
							everything.
						</p>

						{GROUPS.map((g) => {
							const items = rows.filter((p) => p.status === g.key);
							return (
								<section class="group" key={g.key}>
									<div class="group-head">
										<h2>
											{g.label} <span class="count mono">{items.length}</span>
										</h2>
										<span class="group-hint mono">{g.hint}</span>
									</div>
									{items.length === 0 ? (
										<p class="empty mono">nothing here yet.</p>
									) : (
										<ul class="plist">
											{items.map((p) => (
												<li class="prow" key={p.id}>
													<div class="pmain">
														<span class="ptitle">{p.title || p.id}</span>
														<span class="pmeta mono">
															{p.id} · {p.cluster}
															{p.year ? ' · ' + p.year : ''} · order {p.sort_order ?? 100}
															{p.source === 'github' && <span class="tag">github</span>}
														</span>
													</div>
													<div class="pactions">
														<Form action={setStatus} class="statusform">
															<input type="hidden" name="id" value={p.id} />
															<label class="sr-only" for={`s-${p.id}`}>
																status for {p.title || p.id}
															</label>
															<select
																id={`s-${p.id}`}
																name="status"
																onChange$={(_, el) => el.form?.requestSubmit()}
															>
																{GROUPS.map((g2) => (
																	<option key={g2.key} value={g2.key} selected={p.status === g2.key}>
																		{g2.label}
																	</option>
																))}
															</select>
														</Form>
														<button
															type="button"
															class="btn btn--ghost"
															onClick$={() => {
																flash.value = null;
																editingId.value = p.id;
															}}
														>
															edit
														</button>
													</div>
												</li>
											))}
										</ul>
									)}
								</section>
							);
						})}
					</>
				)}
			</main>
		</div>
	);
});

export const head: DocumentHead = {
	title: 'admin, adam portfolio',
	meta: [{ name: 'robots', content: 'noindex, nofollow' }]
};
